version: "3.8"
services:
  postgresql:
    image: postgres:12.1
    volumes:
      - "db:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pingpong_development
      POSTGRES_HOST_AUTH_METHOD: trust
  rails:
    build: ./rails/.
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
      - redis
    environment:
      FT_ID: 611065ccd70b922fb3881e25d60a01a54b5fffac97fdad54a8e7182d6b5aa0c5
      FT_SECRET: 3d717f3d4b9d2f2b18d0c125e5ad1daef1fc864df7ef1d69e31de147c6557210
      REDIS_DB: 0
      REDIS_URL: redis://redis
      REDIS_PORT: 6379
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  db:
