development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "REDIS_DB" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "REDIS_DB" } %>
  channel_prefix: app_production
