default: &default
  adapter: postgresql
  encoding: unicode
  host: postgresql
  username: root
  password: root
  pool: 5

development:
  <<: *default
  database: pingpong_development


test:
  <<: *default
  database: pingpong_test